### PR TITLE
feat(infra): updating GHToken in renovate workflows [CLK-230021]

### PR DESCRIPTION
**Pull request by jeisson-clickup**
# Resume

Updating GitHub Token in **renovate** workflows o use the new Organization secret 'RENOVATEBOT_GITHUB_TOKEN'

Related tasks:
- [CLK-230021](https://staging.clickup.com/t/333/CLK-230021)
- [CLK-228826](https://staging.clickup.com/t/333/CLK-228826)

### CODE REVIEW

**Comment by jeisson-clickup** [comment]
Test without `renovate` label
image

**Comment by jeisson-clickup** [comment]
Test with the `renovate` label
image.
**cdk-update-tracker** project
image

**Review by mattlewis92 — APPROVED** [review]
LGTM!!

**Review by ahammond — APPROVED** [review]

**Comment by jeisson-clickup** [comment]
@ahammond  At this moment, we have [this parameter ](https://github.com/time-loop/clickup-projen/blob/main/src/add-to-project.ts#L7) as a constant. Still, if we want, we can define one environment variable per repository with the value of the specific project to where we want to add the PR record.

currently
```javascript
          with: {
              // github project url
              'project-url': `https://github.com/orgs/time-loop/projects/${GITHUB_PROJECT_NUMBER}`,
              'github-token': '${{ secrets.RENOVATEBOT_GITHUB_TOKEN }}',
              labeled: DEFAULT_RENOVATE_PR_LABEL,
            },
```

With a gitHub environment variables or secret

```javascript
          with: {
              // github project url
              'project-url': `https://github.com/orgs/time-loop/projects/${{ secrets.GITHUB_PROJECT_NUMBER }}`,
              'github-token': '${{ secrets.RENOVATEBOT_GITHUB_TOKEN }}',
              labeled: DEFAULT_RENOVATE_PR_LABEL,
            },
```

**Pull request merged**
